version: "3.9"

services:
  api:
    build: ./app
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
